# Generated by Django 3.2.8 on 2021-10-27 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Libros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('faculty', models.IntegerField(choices=[(0, 'N/A'), (1, 'Ciencia y Tecnología'), (2, 'Bellas Artes'), (3, 'Educación'), (4, 'Ciencias Sociales'), (5, 'Ingeniería')], null=0)),
                ('abstract', models.TextField(blank=True)),
                ('editorial', models.CharField(blank=True, max_length=50)),
                ('author_or_authors', models.CharField(blank=True, max_length=250)),
                ('key_words', models.CharField(blank=True, max_length=100)),
                ('URL', models.URLField(blank=True)),
                ('file', models.FileField(blank=True, upload_to='files/')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
