# Generated by Django 3.2.8 on 2021-10-27 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libros', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Libros',
            new_name='librosmodel',
        ),
    ]
